server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: demo

# =======================================
# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
# =======================================
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_api_zoonosys
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:senha}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# =======================================
# CONFIGURAÇÕES DE SEGURANÇA DA API (JWT)
# =======================================
api:
  security:
    token:
      secret-key: ${TOKEN_SECRET_KEY}
      issuer: ${TOKEN_ISSUER}

# =======================================
# CONFIGURAÇÕES SPRINGDOC (OpenAPI/Swagger)
# =======================================
springdoc:
  api-docs:
    path: /docs
    pathToMatch: /api/**
  swagger-ui:
    use-root-path: true

# =======================================
# CONFIGURAÇÕES BÁSICAS DE E-MAIL (JavaMailSender)
# =======================================
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
             enable: true
          debug: true

# =======================================
# ENDEREÇO DE E-MAIL QUE APARECERÁ COMO REMETENTE
# =======================================
  mail-from:
    address: noreply@zoonosys.com

# =======================================
# CONFIGURAÇÃO DO FRONT-END
# =======================================
app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}